### ISSUE TITLE
How to save the auth token to avoid constantly pairing?

### ISSUE THREAD

**Issue by techsmartteam** [Aymkdn/assistant-freebox-cloud#142]
How can we save and send the token of the TV so that the next time of connection we don't need to pair again?

**Comment by Aymkdn** [comment]
The token is only valid once, and it permits to approve the SSL certificate you created. Once your SSL certificate has been accepted (because of the pairing process), you don't need the token anymore, and you don't need to pair again. You only need to use the same SSL certificate moving forward, and the Android TV will automatically accept the commands.

**Comment by techsmartteam** [comment]
Thank you very much for your response, I appreciate your help!
Actually what I meant is that after we disconnect from the device, every time we connect again how can we just get connected without pairing again, it's like the device just recognizes our phone. Currently, in 1 session the TV can recognize the phone, but after disconnecting it make us pair again to be connected.

**Comment by Aymkdn** [comment]
You can try to reboot the TV: sometimes a reboot is required to avoid this case.

And make sure you always provide the same certificate.

**Comment by techsmartteam** [comment]
Great, it works now. Thank you so much for your help. It saves me lots of time and headache!
